import styles from './styles.module.css'
import '../../styles/global.css'
import { Roboto } from 'next/font/google'
import Header from '@/components/Header'
 
const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr" className={roboto.className}>
      <body className={styles.container}>
        <Header/>
        <main>{children}</main>
        <footer><h1>Footer</h1></footer>
      </body>
    </html>
  );
}
